471007=com.suning.api.rsf.service.ApiRemoteMapService@faloan-repay@execute
176001=com.suning.api.rsf.service.ApiRemoteMapService@faloan-advanceAccountRefund@execute
176002=com.suning.api.rsf.service.ApiRemoteMapService@faloan-advanceAccountCharge@execute
471008=com.suning.api.rsf.service.ApiRemoteMapService@faloan-specialRepay@execute